import { Quicksand } from 'next/font/google'
import './globals.css'

const myFont = Quicksand({ 
  subsets: ['latin'],
  variable: "--my-font"
})

export const metadata = {
  title: 'Stage Striking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} font-sans bg-black`}>{children}</body>
    </html>
  )
}
